# Generated by Django 6.0.6 on 2026-06-06 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='contents',
            new_name='content',
        ),
    ]
